apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-gateway-srv
  name: web-gateway-srv
spec:
  type: ClusterIP
  ports:
    - name: web-gateway-srv
      port: 80
      targetPort: 80
  selector:
    app: web-gateway-app


