apiVersion: v1
kind: Service
metadata:
  name: admin-app-srv
  labels:
    app: admin-app-srv
spec:
  type: ClusterIP
  ports:
    - name: admin-app-srv
      port: 80
      targetPort: 80
  selector:
    app: admin-app-depl
