apiVersion: v1
kind: Service
metadata:
  name: admin-postgres-srv
  labels:
    app: admin-postgres-srv

spec:
  type: ClusterIP
  ports:
    - name: admin-postgres-srv
      port: 5432
      targetPort: 5432
  selector:
    app: admin-postgres-depl
