apiVersion: v1
kind: Service
metadata:
  name: board-app-srv
  labels:
    app: board-app-srv
spec:
  type: ClusterIP
  ports:
    - name: board-app-srv
      port: 80
      targetPort: 80
  selector:
    app: board-app-depl

