apiVersion: v1
kind: Service
metadata:
  name: board-postgres-srv
  labels:
    app: board-postgres-srv

spec:
  type: ClusterIP
  ports:
    - name: board-postgres-srv
      port: 5432
      targetPort: 5432
  selector:
    app: board-postgres-depl

