apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspace-neo4j-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workspace-neo4j
  template:
    metadata:
      labels:
        app: workspace-neo4j
    spec:
      containers:
        - name: workspace
          image: nginx:1.25.0
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
         