apiVersion: v1
kind: Service
metadata:
  labels:
    app: workspace-app-srv
  name: workspace-app-srv
spec:
  type: ClusterIP
  ports:
    - name: "workspace-srv"
      port: 80
      targetPort: 80
  selector:
    app: workspace-app

